### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kermitdafrog8** [bldewolf/libkpass#1]
I get the following error when running make on Slackware --current on ARM (Raspberry Pi3)

CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.13 -I m4
/bin/sh: aclocal-1.13: command not found
make: *** [Makefile:632: aclocal.m4] Error 127

I have aclocal version 1.16.1 installed.

**Comment by bldewolf** [comment]
Hi!  I haven't touched this repo in a long time.  The release tarballs still built so I was confused why the repo checkout won't build.  It looks like it decides to try to rebuild everything because of timestamps from when the repo clone happens, so we can convince it to not do that by fixing the timestamps on a few files by running: `touch Makefile.in aclocal.m4`
